services:
  setup:
    image: alpine
    container_name: setup
    command: >
      sh -c "
      mkdir -p /data/web/static /data/web/media &&
      chmod -R 777 /data/web
      "
    volumes:
      - ./data:/data

  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      setup:
        condition: service_completed_successfully
      psql:
        condition: service_started

  psql:
    container_name: psql
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env