# Generated by Django 6.0.5 on 2026-05-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_sitesetup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_hfooter',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
    ]
