# Generated by Django 6.0.5 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_descritpion',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_description',
            field=models.BooleanField(default=True),
        ),
    ]
